export type AiModelTier = "small" | "medium" | "large";
export type AiModelCapability =
  | "multilingual"
  | "reasoning"
  | "low-latency"
  | "long-context"
  | "english-focused"
  | "apple-silicon";

export interface AiModelCatalogItem {
  id: string;
  label: string;
  tier: AiModelTier;
  source: "ollama-registry";
  estimatedDisk: string;
  recommendedRam: string;
  recommendedContext: string;
  defaultNumCtx: number;
  maxNumCtx: number;
  defaultNumPredict: number;
  description: string;
  /** German description, shown when the app language is "de". Falls back to `description`. */
  descriptionDe?: string;
  recommended: boolean;
  capabilities?: AiModelCapability[];
}

export const AI_MODEL_CATALOG: AiModelCatalogItem[] = [
  // ── Tier 1: Läuft auf jedem Laptop (8 GB RAM genügen) ──
  {
    id: "granite4.2:3b",
    label: "Granite 4.2 3B",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~2,2 GB",
    recommendedRam: "VRAM: 4 GB · CPU: 8+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 8192,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "IBM's compact Granite 4.2 model with solid multilingual support and efficient tool use — runs smoothly on very weak hardware.",
    descriptionDe: "IBMs kompaktes Granite-4.2-Modell mit solider Mehrsprachigkeit und effizientem Tool-Einsatz – läuft flüssig auf sehr schwacher Hardware.",
    recommended: false,
    capabilities: ["multilingual", "low-latency"],
  },
  {
    id: "qwen3.5:4b",
    label: "Qwen 3.5 4B",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~3,4 GB",
    recommendedRam: "VRAM: 6-8 GB · CPU: 12+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Compact multilingual model with 201 languages and a huge 256K context — ideal for simple translations and classroom questions on weak hardware.",
    descriptionDe: "Kompaktes Multilingual-Modell mit 201 Sprachen und riesigem 256K-Kontext – ideal für einfache Übersetzungen und Unterrichtsfragen auf schwacher Hardware.",
    recommended: false,
    capabilities: ["multilingual", "low-latency", "long-context"],
  },
  {
    id: "qwen3.5:4b-mlx",
    label: "Qwen 3.5 4B (MLX)",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~4.0 GB",
    recommendedRam: "Apple memory: 12 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Qwen 3.5 4B as an MLX build — tuned for Apple Silicon's unified memory. Noticeably faster on M1–M4 Macs than the standard build; not for Windows/Linux PCs.",
    descriptionDe: "Qwen 3.5 4B als MLX-Build – nutzt den vereinheitlichten Speicher von Apple Silicon optimal aus. Auf M1–M4-Macs spürbar schneller als die Standard-Version; nicht für Windows/Linux-PCs.",
    recommended: false,
    capabilities: ["multilingual", "low-latency", "long-context", "apple-silicon"],
  },
  {
    id: "granite4.2:8b",
    label: "Granite 4.2 8B",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~5,3 GB",
    recommendedRam: "VRAM: 6-8 GB · CPU: 12+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Balanced Granite 4.2 profile with 128K context and reliable multilingual support — one of the most current options for laptops without a dedicated GPU.",
    descriptionDe: "Ausgewogenes Granite-4.2-Profil mit 128K-Kontext und zuverlässiger Mehrsprachigkeit – eine der aktuellsten Optionen für Laptops ohne dedizierte GPU.",
    recommended: false,
    capabilities: ["multilingual", "low-latency"],
  },
  {
    id: "lfm2.5:8b",
    label: "LFM 2.5 8B",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~5,2 GB",
    recommendedRam: "VRAM: 6-8 GB · CPU: 12+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Ultra-fast edge model from Liquid AI, optimized for low latency and a small memory footprint — ideal for snappy answers and simple text work.",
    descriptionDe: "Ultraschnelles Edge-Modell von Liquid AI, optimiert für niedrige Latenz und geringen Speicherbedarf – ideal für flotte Antworten und einfache Textarbeit.",
    recommended: false,
    capabilities: ["multilingual", "low-latency"],
  },
  {
    id: "ministral-3:8b",
    label: "Ministral 3 8B",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~6,0 GB",
    recommendedRam: "VRAM: 8-10 GB · CPU: 16+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Compact Ministral 3 model from Mistral with 256K context and good multilingual support — an efficient European alternative for 16 GB machines.",
    descriptionDe: "Kompaktes Ministral-3-Modell von Mistral mit 256K-Kontext und guter Mehrsprachigkeit – effiziente europäische Alternative für 16-GB-Rechner.",
    recommended: false,
    capabilities: ["multilingual", "low-latency", "long-context"],
  },

  // ── Tier 2: Empfohlen für die meisten (16 GB RAM / 12 GB VRAM) ──
  {
    id: "qwen3.5:9b",
    label: "Qwen 3.5 9B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~6,6 GB",
    recommendedRam: "VRAM: 8-12 GB · CPU: 16+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "RECOMMENDED DEFAULT MODEL: Best multilingual support (201 languages), thinking mode, huge 256K context and excellent German quality — ideal for lesson planning, chat and translation.",
    descriptionDe: "EMPFOHLENES STANDARD-MODELL: Beste Mehrsprachigkeit (201 Sprachen), Thinking-Unterstützung, riesiger 256K-Kontext und exzellente Deutschqualität – ideal für Unterrichtsplanung, Chat und Übersetzung.",
    recommended: true,
    capabilities: ["multilingual", "reasoning", "low-latency", "long-context"],
  },
  {
    id: "qwen3.5:9b-mlx",
    label: "Qwen 3.5 9B (MLX)",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~8.9 GB",
    recommendedRam: "Apple memory: 16 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Qwen 3.5 9B as an MLX build — the recommended default, tuned for Apple Silicon's unified memory. The fastest way to run this model on M1–M4 Macs.",
    descriptionDe: "Qwen 3.5 9B als MLX-Build – der empfohlene Standard, optimiert für den vereinheitlichten Speicher von Apple Silicon. Der schnellste Weg, dieses Modell auf M1–M4-Macs zu betreiben.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "low-latency", "long-context", "apple-silicon"],
  },
  {
    id: "gemma4:e2b",
    label: "Gemma 4 E2B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~7,2 GB",
    recommendedRam: "VRAM: 8-10 GB · CPU: 16+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Fast Gemma 4 profile with a strong speed/quality ratio — good for quick rewrites and chat on moderate hardware.",
    descriptionDe: "Schnelles Gemma-4-Profil mit starkem Speed/Qualitäts-Verhältnis – gut für schnelle Überarbeitungen und Chat bei moderater Hardware.",
    recommended: false,
    capabilities: ["multilingual", "low-latency", "reasoning", "long-context"],
  },
  {
    id: "gemma4:e2b-mlx",
    label: "Gemma 4 E2B (MLX)",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~7.5 GB",
    recommendedRam: "Apple memory: 12 GB+",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Gemma 4 E2B as an MLX build — tuned for Apple Silicon's unified memory. The tiny Gemma runs noticeably smoother on M1–M4 Macs than the standard build.",
    descriptionDe: "Gemma 4 E2B als MLX-Build – optimiert für den vereinheitlichten Speicher von Apple Silicon. Das kompakte Gemma läuft auf M1–M4-Macs spürbar flüssiger als die Standard-Version.",
    recommended: false,
    capabilities: ["multilingual", "low-latency", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "gemma4:12b",
    label: "Gemma 4 12B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~7,6 GB",
    recommendedRam: "VRAM: 8-10 GB · CPU: 16+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Current Gemma 4 profile with 256K context and thinking mode — noticeably better quality than E4B at a similar memory footprint, ideal for most 16 GB machines.",
    descriptionDe: "Aktuelles Gemma-4-Profil mit 256K-Kontext und Thinking-Modus – deutlich mehr Qualität als E4B bei ähnlichem Speicherbedarf, ideal für die meisten 16-GB-Rechner.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "gemma4:12b-mlx",
    label: "Gemma 4 12B (MLX)",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~7.7 GB",
    recommendedRam: "Apple memory: 16 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 16384,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Gemma 4 12B as an MLX build — 256K context and thinking mode, tuned for Apple Silicon's unified memory. Noticeably faster on M1–M4 Macs than the standard build.",
    descriptionDe: "Gemma 4 12B als MLX-Build – 256K-Kontext und Thinking-Modus, optimiert für den vereinheitlichten Speicher von Apple Silicon. Auf M1–M4-Macs spürbar schneller als die Standard-Version.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "ministral-3:14b",
    label: "Ministral 3 14B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~9,1 GB",
    recommendedRam: "VRAM: 10-12 GB · CPU: 20+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Mid-size Ministral 3 model with 256K context and strong multilingual support — the best 14B option for laptops with 16 GB RAM.",
    descriptionDe: "Mittelgroßes Ministral-3-Modell mit 256K-Kontext und starker Mehrsprachigkeit – die beste 14B-Option für Laptops mit 16 GB RAM.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "gemma4:e4b",
    label: "Gemma 4 E4B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~9,6 GB",
    recommendedRam: "VRAM: 10-14 GB · CPU: 24+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Solid all-rounder for more extensive classroom chats and multilingual tasks — proven and reliable.",
    descriptionDe: "Solider Allrounder für umfangreichere Unterrichts-Chats und mehrsprachige Aufgaben – bewährt und zuverlässig.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "gemma4:e4b-mlx",
    label: "Gemma 4 E4B (MLX)",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~9.5 GB",
    recommendedRam: "Apple memory: 16 GB+",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Gemma 4 E4B as an MLX build — tuned for Apple Silicon's unified memory. Solid all-round performance, noticeably faster on M1–M4 Macs than the standard build.",
    descriptionDe: "Gemma 4 E4B als MLX-Build – optimiert für den vereinheitlichten Speicher von Apple Silicon. Solider Allrounder, auf M1–M4-Macs spürbar schneller als die Standard-Version.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "gpt-oss:20b",
    label: "GPT-OSS 20B",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~14 GB",
    recommendedRam: "VRAM: 16+ GB · CPU: 32+ GB RAM",
    recommendedContext: "Max context: 128K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 131072,
    defaultNumPredict: 2048,
    description: "OpenAI open-weight model with pronounced reasoning and adjustable thinking intensity — the strongest local option for GPUs with 16 GB VRAM.",
    descriptionDe: "OpenAI-Open-Weight-Modell mit ausgeprägtem Reasoning und einstellbarer Denkintensität – stärkste lokale Option für GPUs mit 16 GB VRAM.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },

  // ── Tier 3: Für High-End-GPUs (24 GB VRAM, z. B. RTX 4090) ──
  {
    id: "qwen3.6:27b",
    label: "Qwen 3.6 27B",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~18 GB",
    recommendedRam: "VRAM: 20-24 GB · CPU: 32+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Qwen 3.6 27B with 256K context, thinking mode and excellent multilingual support — current generation for demanding lesson planning.",
    descriptionDe: "Qwen 3.6 27B mit 256K-Kontext, Thinking-Modus und exzellenter Mehrsprachigkeit – aktuelle Generation für anspruchsvolle Unterrichtsplanung.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "qwen3.6:27b-mlx",
    label: "Qwen 3.6 27B (MLX)",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~19 GB",
    recommendedRam: "Apple memory: 32 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Qwen 3.6 27B as an MLX build — thinking mode and excellent multilingual quality, tuned for Apple Silicon's unified memory. For M-series Macs with 32 GB+.",
    descriptionDe: "Qwen 3.6 27B als MLX-Build – Thinking-Modus und exzellente Mehrsprachigkeit, optimiert für den vereinheitlichten Speicher von Apple Silicon. Für M-Macs mit 32 GB+.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "qwen3.8:27b",
    label: "Qwen 3.8 27B",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~18 GB",
    recommendedRam: "VRAM: 20-24 GB · CPU: 32+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "The newest Qwen flagship for local systems: first-class reasoning, 256K context and outstanding German quality.",
    descriptionDe: "Neuestes Qwen-Flaggschiff für lokale Systeme: erstklassiges Reasoning, 256K-Kontext und herausragende Deutschqualität.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "qwen3.8:27b-mlx",
    label: "Qwen 3.8 27B (MLX)",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~18 GB",
    recommendedRam: "Apple memory: 32 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Qwen 3.8 27B as an MLX build — the newest Qwen flagship, tuned for Apple Silicon's unified memory. For M-series Macs with 32 GB+ unified memory.",
    descriptionDe: "Qwen 3.8 27B als MLX-Build – das neueste Qwen-Flaggschiff, optimiert für den vereinheitlichten Speicher von Apple Silicon. Für M-Macs mit 32 GB+ vereinheitlichtem Speicher.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "gemma4:26b",
    label: "Gemma 4 26B",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~19 GB",
    recommendedRam: "VRAM: 20-24 GB · CPU: 48+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "High-capacity Gemma 4 profile for deep reasoning, multilingual tasks and long, structured outputs — for high-end systems.",
    descriptionDe: "Hochkapazitives Gemma-4-Profil für tiefgreifendes Reasoning, mehrsprachige Aufgaben und lange, strukturierte Ausgaben – für Highend-Systeme.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "gemma4:26b-mlx",
    label: "Gemma 4 26B (MLX)",
    tier: "medium",
    source: "ollama-registry",
    estimatedDisk: "~18 GB",
    recommendedRam: "Apple memory: 24 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 1024,
    description: "Gemma 4 26B as an MLX build — the efficient MoE variant, tuned for Apple Silicon's unified memory. For M-series Macs with 24 GB+ unified memory.",
    descriptionDe: "Gemma 4 26B als MLX-Build – die effiziente MoE-Variante, optimiert für den vereinheitlichten Speicher von Apple Silicon. Für M-Macs mit 24 GB+ vereinheitlichtem Speicher.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "gemma4:31b",
    label: "Gemma 4 31B",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~20 GB",
    recommendedRam: "VRAM: 24 GB · CPU: 48+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Largest local dense Gemma 4 model with 256K context — top quality for GPUs with 24 GB VRAM.",
    descriptionDe: "Größtes lokales Gemma-4-Modell (dense) mit 256K-Kontext – Spitzenqualität für GPUs mit 24 GB VRAM.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "gemma4:31b-mlx",
    label: "Gemma 4 31B (MLX)",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~19 GB",
    recommendedRam: "Apple memory: 32 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 131072,
    defaultNumPredict: 1024,
    description: "Gemma 4 31B as an MLX build — the largest dense Gemma, tuned for Apple Silicon's unified memory. For M-series Macs with 32 GB+ unified memory.",
    descriptionDe: "Gemma 4 31B als MLX-Build – das größte dense Gemma, optimiert für den vereinheitlichten Speicher von Apple Silicon. Für M-Macs mit 32 GB+ vereinheitlichtem Speicher.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },
  {
    id: "qwen3.6:35b",
    label: "Qwen 3.6 35B",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~24 GB",
    recommendedRam: "VRAM: 24 GB · CPU: 48+ GB RAM",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Qwen 3.6 35B for 24 GB GPUs — maximum local quality, 256K context and strong reasoning for the most demanding educational tasks.",
    descriptionDe: "Qwen 3.6 35B für 24-GB-GPUs – maximale lokale Qualität, 256K-Kontext und starkes Reasoning für anspruchsvollste pädagogische Aufgaben.",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context"],
  },
  {
    id: "qwen3.6:35b-mlx",
    label: "Qwen 3.6 35B (MLX)",
    tier: "large",
    source: "ollama-registry",
    estimatedDisk: "~24 GB",
    recommendedRam: "Apple memory: 32 GB+",
    recommendedContext: "Max context: 256K tokens",
    defaultNumCtx: 32768,
    maxNumCtx: 262144,
    defaultNumPredict: 2048,
    description: "Qwen 3.6 35B as an MLX build — maximum local quality, tuned for Apple Silicon's unified memory. For high-end M-series Macs (M2 Ultra/M3 Max/M4 Max class).",
    descriptionDe: "Qwen 3.6 35B als MLX-Build – maximale lokale Qualität, optimiert für den vereinheitlichten Speicher von Apple Silicon. Für High-End-M-Macs (M2 Ultra/M3 Max/M4 Max-Klasse).",
    recommended: false,
    capabilities: ["multilingual", "reasoning", "long-context", "apple-silicon"],
  },

  // ── Embedding model (not used for chat) ──
  {
    id: "bge-m3",
    label: "BGE-M3 (Embedding)",
    tier: "small",
    source: "ollama-registry",
    estimatedDisk: "~1.2 GB",
    recommendedRam: "VRAM: 4-6 GB · CPU: 8+ GB RAM",
    recommendedContext: "Max input: 8192 tokens",
    defaultNumCtx: 8192,
    maxNumCtx: 8192,
    defaultNumPredict: 128,
    description: "Multilingual embedding model for RAG (Retrieval-Augmented Generation). Produces 1024-dimensional vectors and supports 100+ languages — ideal for knowledge base search.",
    descriptionDe: "Multilingual embedding model für RAG (Retrieval-Augmented Generation). Erzeugt 1024-dimensionale Vektoren und unterstützt 100+ Sprachen – ideal für die Wissensdatenbank-Suche.",
    recommended: true,
    capabilities: ["multilingual"],
  },
];

export const DEFAULT_AI_MODEL_ID = "qwen3.5:9b";
export const EMBEDDING_MODEL_ID = "bge-m3";

export const DEFAULT_MODEL_RUNTIME_DEFAULTS = {
  defaultNumCtx: 6144,
  defaultNumPredict: 896,
};

const AI_THINKING_MODEL_IDS = new Set<string>([
  "qwen3.5:4b",
  "qwen3.5:9b",
  "gemma4:e2b",
  "gemma4:e4b",
  "gemma4:12b",
  "gemma4:26b",
  "gemma4:31b",
  "qwen3.6:27b",
  "qwen3.6:35b",
  "qwen3.8:27b",
    "qwen3.5:4b-mlx",
  "qwen3.5:9b-mlx",
  "gemma4:e2b-mlx",
  "gemma4:e4b-mlx",
  "gemma4:12b-mlx",
  "gemma4:26b-mlx",
  "gemma4:31b-mlx",
  "qwen3.6:27b-mlx",
  "qwen3.6:35b-mlx",
  "qwen3.8:27b-mlx",
  "gpt-oss:20b",
]);

export function doesAiModelSupportThinking(modelId: string): boolean {
  return AI_THINKING_MODEL_IDS.has(modelId);
}

export function getAiModelCatalogItem(modelId: string): AiModelCatalogItem | undefined {
  return AI_MODEL_CATALOG.find((model) => model.id === modelId);
}

export function getAiModelRuntimeDefaults(modelId: string): {
  defaultNumCtx: number;
  maxNumCtx: number;
  defaultNumPredict: number;
} {
  const item = getAiModelCatalogItem(modelId);
  if (!item) {
    return { ...DEFAULT_MODEL_RUNTIME_DEFAULTS, maxNumCtx: 8192 };
  }

  return {
    defaultNumCtx: item.defaultNumCtx,
    maxNumCtx: item.maxNumCtx,
    defaultNumPredict: item.defaultNumPredict,
  };
}
